DATAS SEGMENT                        
  FILENAME DB 'Input3.txt',0
  HANDLE DW ?
  COUNT DW ?
  NUM DW 200 DUP ('$')
  TEXT1 DB 180 DUP ('$')
  TEXT2 DB 180 DUP ('$')
  TEXT3 DB 180 DUP ('$')
  TEXT4 DB 100 DUP ('$')
DATAS ENDS

CODES SEGMENT
    ASSUME CS:CODES,DS:DATAS
START:
  MOV AX,DATAS
  MOV DS,AX

  MOV AH,3DH
  MOV AL,0
  LEA DX,FILENAME
  INT 21H;打开文件
  MOV HANDLE,AX

  MOV BX,HANDLE
  MOV CX,258H
  LEA DX,TEXT1
  MOV AH,3FH
  INT 21H    ;读取600个字节到缓冲区

  MOV SI,0  ;TEXT偏移量
  MOV DI,0  ;NUM偏移量
  MOV BX,0  ;记录存了几个数,改了以后马上转存
  MOV COUNT,BX
  MOV CL,0AH ;数字10
  MOV AX,0  ;存数
  MOV DL,TEXT1[SI]  ;DL存储字符

LOOPER:
  CMP DL,'-'
  JE MINUS
  CMP DL,20H  ;空格
  JE NEXT1
  CMP DL,'$'
  JE NEXT1
  SUB DL,30H ;ASCII转数字
  MUL CL
  MOV DH,0
  ADD AX,DX;高位乘10加上低位
  ADD SI,01H
  MOV DL,TEXT1[SI]
  JMP LOOPER

MINUS:
  ADD SI,01H
  MOV DL,TEXT1[SI]
  CMP DL,20H  ;空格
  JE NEXT3
  CMP DL,'$'
  JE NEXT3
  SUB DL,30H ;ASCII转数字
  MUL CL
  MOV DH,0
  ADD AX,DX;高位乘10加上低位
  JMP MINUS
      
NEXT1:
  ADD AX,400H ;正数加1024
NEXT2:
  MOV NUM[DI],AX
  MOV BX,COUNT
  ADD BX,01H
  MOV COUNT,BX
  ADD DI,02H  ;DW
  ADD SI,01H  ;DB
  MOV AX,0
  MOV DL,TEXT1[SI]
  CMP DL,'$' ;全部读完
  JNE LOOPER
  JE  SORTSTART
NEXT3:
  MOV BX,400H
  SUB BX,AX
  MOV AX,BX;负数用1024减它
  JMP NEXT2

  
SORTSTART:
  MOV CX,0 ;外层循环
  MOV DX,0;内层循环   
  MOV AX,COUNT
  MOV BL,02H
  MUL BL   ;DW,所以循环条件和步长乘2
  MOV COUNT,AX
JUDGE:
  MOV BX,COUNT
  SUB BX,02H  
  SUB BX,CX
  CMP DX,BX
  JNE SORT
  ADD CX,02H
  MOV BX,COUNT
  SUB BX,02H
  CMP CX,BX
  JE  OUTPUT
  MOV DX,0
SORT:
  MOV DI,DX
  MOV SI,DX
  ADD SI,02H
  MOV AX,NUM[DI]
  MOV BX,NUM[SI]
  CMP AX,BX
  JA  SWAP
  ADD DX,02H
  JMP JUDGE
SWAP:
  MOV NUM[SI],AX
  MOV NUM[DI],BX
  ADD DX,02H
  JMP JUDGE

OUTPUT:
  MOV DI,0
OUTPUTSTART:
  MOV AX,NUM[DI]
  CMP AX,'$'
  JE  QUIT
  CMP AX,3FFH ;1023
  JA  NOTMINUS
  MOV BX,400H
  SUB BX,AX ;负数用1024减它
  MOV DL,'-'
  MOV AH,02H
  INT 21H
  MOV AX,BX
  JMP DIVSTART
NOTMINUS:
  SUB AX,400H ;正数减掉1024
DIVSTART:
  CMP AX,3E7H ;999
  JA  THOUSANDS
  CMP AX,63H;99
  JA  HUNDREDS
  CMP AX,09H;9
  JA  TENS
  MOV DL,AL
  MOV AH,02H
  ADD DL,30H
  INT 21H
  MOV DL,20H
  INT 21H
  ADD DI,02H
  JMP OUTPUTSTART
THOUSANDS: ;最大为1023，仍然为8位
  MOV DX,0
  MOV CX,3E8H ;1000
  DIV CX
  MOV BX,DX
  MOV DL,'1'  ;商一定是1
  MOV AH,02H
  INT 21H
  MOV AX,BX  ;余数
HUNDREDS: ;大于100小于1000
  MOV CL,64H;100
  DIV CL
  MOV BX,AX
  MOV DL,BL
  MOV AH,02H
  ADD DL,30H
  INT 21H
  MOV AL,BH ;余数小于100，8位
  MOV AH,0
TENS: ;大于10小于100
  MOV CL,0AH;10
  DIV CL
  MOV BX,AX
  MOV DL,BL
  MOV AH,02H
  ADD DL,30H
  INT 21H
  MOV DL,BH
  ADD DL,30H
  INT 21H
  MOV DL,20H
  INT 21H
  ADD DI,02H
  JMP OUTPUTSTART
  
QUIT:
  MOV BX,HANDLE
  MOV AH,3EH
  INT 21H   ;关闭文件
  
  MOV  AX,4C00H
  INT  21H
CODES ENDS
END START
  